spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: rajesh353
    url: jdbc:mysql://localhost:3306/MajorDB
    username: root
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
